name: Docker

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_publish_containers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout repo
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

  with:

    submodules: recursive

      - name: Build/push

        uses: whoan/docker-build-with-cache-action@v5

        with:

          registry: ghcr.io

          image_name: ${{ github.actor }}/GSOC22

          username: ${{ github.actor }}

          password: ${{ secrets.GITHUB_TOKEN }}